apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: mlops-demo-dev-grafana
  namespace: mlops-demo-dev
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: true
    log:
      level: warn
      mode: console
    security:
      admin_password: r3dh4t1!
      admin_user: grafana_admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
---
apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: mlops-demo-grafanadatasource
  namespace: mlops-demo-dev
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        timeInterval: 5s
      name: Prometheus
      type: prometheus
      url: https://prometheus-k8s-openshift-monitoring.apps.cluster-7mnq4.7mnq4.sandbox1440.opentlc.com
      version: 1
  name: mlops-demo-datasources.yaml