apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datascience-pipelines-instance
spec:
  destination:
    namespace: mlops-demo-pipelines
    server: https://kubernetes.default.svc
  project: mlops-demo-pipelines
  source:
    path: environments/pipelines/components/datascience-pipelines/overlays/default
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
