apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: seldon-core-analytics
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: seldon-core-analytics-dev
              namespace: mlops-demo-dev
              project: mlops-demo-dev
              path: environments/dev/charts/seldon-core-analytics
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: seldon-core-analytics-test
              namespace: mlops-demo-test
              project: mlops-demo-test
              path: environments/test/charts/seldon-core-analytics
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: seldon-core-analytics-prod
              namespace: mlops-demo-prod
              project: mlops-demo-prod
              path: environments/prod/charts/seldon-core-analytics
  template:
    metadata:
      name: '{{values.name}}'
    spec:
      destination:
        namespace: '{{values.namespace}}'
        server: https://kubernetes.default.svc
      project: '{{values.project}}'
      source:
        path: '{{values.path}}'
        repoURL: patch-me-see-tenant-overlays
        targetRevision: patch-me-see-tenant-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
