apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: grafana-dev
              namespace: mlops-demo-dev
              project: mlops-demo-dev
              path: environments/dev/operators/grafana/aggregate/overlays/default/
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: grafana-test
              namespace: mlops-demo-test
              project: mlops-demo-test
              path: environments/test/operators/grafana/aggregate/overlays/default/
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: grafana-prod
              namespace: mlops-demo-prod
              project: mlops-demo-prod
              path: environments/prod/operators/grafana/aggregate/overlays/default/
  template:
    metadata:
      name: '{{values.name}}'
    spec:
      destination:
        namespace: '{{values.namespace}}'
        server: https://kubernetes.default.svc
      project: '{{values.project}}'
      source:
        path: '{{values.path}}'
        repoURL: patch-me-see-tenant-overlays
        targetRevision: patch-me-see-tenant-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
