apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-demo-mlflow-server
spec:
  destination:
    namespace: mlops-demo-datascience
    server: https://kubernetes.default.svc
  project: mlops-demo-datascience
  source:
    path: environments/datascience/mlflow-server/
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
