apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: iris-inference-service
spec:
  generators:
    - list:
        elements:
          - cluster: local
            url: https://kubernetes.default.svc
            values:
              name: iris-inference-service-dev
              namespace: mlops-demo-dev
              project: mlops-demo-dev
              path: environments/dev/charts/iris-inference-service
  template:
    metadata:
      name: '{{values.name}}'
    spec:
      destination:
        namespace: '{{values.namespace}}'
        server: https://kubernetes.default.svc
      project: '{{values.project}}'
      source:
        path: '{{values.path}}'
        repoURL: patch-me-see-tenant-overlays
        targetRevision: patch-me-see-tenant-overlays
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
