apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-demo-pipeline-rbac
spec:
  destination:
    namespace: mlops-demo-pipelines
    server: https://kubernetes.default.svc
  project: mlops-demo-pipelines
  source:
    path: components/tekton/rbac/overlays/default/
    repoURL: patch-me-see-tenant-overlays
    targetRevision: patch-me-see-tenant-overlays
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
