apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: iris-training
spec:
  params:
    - default: >-
        https://github.com/rh-intelligent-application-practice/mlops-demo-iris-training-service.git
      description: Iris Training Repo URL
      name: GIT_URL
      type: string
    - default: main
      description: Main Branch
      name: GIT_REVISION
      type: string
    - default: >-
        image-registry.openshift-image-registry.svc:5000/mlops-demo-pipelines/iris-training
      description: Image Stream URL
      name: IMAGE_NAME
      type: string
    - default: 3.9-ubi8
      description: 3.9-ubi8
      name: PYTHON_VERSION
      type: string
    - default: 'https://ds-pipeline-ui-mlops-demo-datascience.apps.cluster-rn5gs.rn5gs.sandbox742.opentlc.com/'
      description: The endpoint URL for Kubeflow
      name: KUBEFLOW_ENDPOINT
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.GIT_URL)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:2b4c4958cabdceffefef68940608f2c7e6774c0b94ba3eb49fa1b9ff0b544e8c
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: s2i-python
      params:
        - name: VERSION
          value: $(params.PYTHON_VERSION)
        - name: PATH_CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'false'
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: BUILDER_IMAGE
          value: >-
            registry.redhat.io/rhel8/buildah@sha256:ac0b8714cc260c94435cab46fe41b3de0ccbc3d93e38c395fa9d52ac49e521fe
        - name: SKIP_PUSH
          value: 'false'
        - name: ENV_VARS
          value: []
      runAfter:
        - git-clone
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
        - name: source
          workspace: source
    - name: execute-kubeflow-pipeline
      params:
        - name: IMAGE
          value: >-
            image-registry.openshift-image-registry.svc:5000/mlops-demo-pipelines/iris-training
        - name: TAG
          value: latest
        - name: SCRIPT
          value: pipelines/iris_pipeline.py
        - name: KUBEFLOW_ENDPOINT
          value: $(params.KUBEFLOW_ENDPOINT)
      runAfter:
        - s2i-python
      taskRef:
        kind: Task
        name: execute-kubeflow-pipeline
  workspaces:
    - name: source
