apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: iris-training
      app.kubernetes.io/component: pipeline
      app.kubernetes.io/instance: iris-training
      app.kubernetes.io/name: iris-training
      app.kubernetes.io/part-of: iris-training
      pipeline.openshift.io/runtime: python
      pipeline.openshift.io/runtime-version: 3.9-ubi8
      pipeline.openshift.io/type: kubernetes

resources:
  - iris-training-imagestream.yaml
  - iris-training-pipeline.yaml
