apiVersion: v2
name: kafka
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "kafka"
    version: "0.1.2"
    repository: "https://rh-datascience-and-edge-practice.github.io/helm-charts/"
