apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: mlops-demo-prod-grafana
  namespace: mlops-demo-prod
spec:
  ingress:
    enabled: true
  config:
    auth:
      disable_signout_menu: true
    log:
      level: warn
      mode: console
    security:
      admin_password: r3dh4t1!
      admin_user: grafana_admin
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana