apiVersion: v2
name: mlflow
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "mlflow-server"
    version: "0.5.2"
    repository: "https://strangiato.github.io/helm-charts/"
