apiVersion: v2
name: kafka
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "kafka"
    version: "0.1.1"
    repository: "https://rh-intelligent-application-practice.github.io/helm-charts/"
