apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: mlops-demo-application-gitops
spec:
  params:
    - name: GIT_REPO
      type: string
      description: The application git repository url
      default: https://github.com/rh-intelligent-application-practice/mlops-demo-application-gitops.git
    - name: GIT_REVISION
      type: string
      default: main
      description: The application git repository revision
  workspaces:
    - name: app-source
  tasks:
    - name: git-clone
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
      - name: url
        value: $(params.GIT_REPO)
      - name: revision
        value: $(params.GIT_REVISION)
      - name: deleteExisting
        value: 'true'
      workspaces:
      - name: output
        workspace: app-source
    - name: generate-tag
      params:
        - name: SHA
          value: ""
      taskRef:
        kind: Task
        name: generate-tag
    - name: update-values
      runAfter:
      - git-clone
      - generate-tag
      taskRef:
        kind: Task
        name: update-values-image-tag
      params:
      - name: fileName
        value: values.yaml
      - name: filePath
        value: environments/dev/charts/iris-inference-service
      - name: imageTag
        value: $(tasks.generate-tag.results.image-tag)
      - name: verbose
        value: "true"
      workspaces:
        - name: source
          workspace: app-source
    - name: git-push-repository
      runAfter:
      - update-values
      taskRef:
        kind: Task
        name: git-push-repository
      params:
      - name: gitRepositoryPath
        value: environments/dev/charts
      - name: gitRepositoryName
        value: iris-inference-service
      - name: gitRepositoryRevision
        value: $(params.GIT_REVISION)
      - name: commitMessage
        value: "Updating Values YAML Image tag to $(tasks.generate-tag.results.image-tag)"
      - name: verbose
        value: "true"
      workspaces:
        - name: source
          workspace: app-source