apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-demo-dev

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  
bases:
  - ../../base

patches:
  - target:
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
    path: patch-channel.yaml
