apiVersion: integreatly.org/v1alpha1
kind: GrafanaDataSource
metadata:
  name: openshift-prometheus
spec:
  datasources:
    - access: proxy
      editable: true
      isDefault: true
      jsonData:
        httpHeaderName1: 'Authorization'
        timeInterval: 5s
        tlsSkipVerify: true
      name: Prometheus
      secureJsonData:
        httpHeaderValue1: 'Bearer $__file{/var/run/secrets/kubernetes.io/serviceaccount/token}'
      type: prometheus
      url: 'https://thanos-querier.openshift-monitoring.svc.cluster.local:9091'
  name: openshift-prometheus-datasources.yaml
