apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: copy-obc
  namespace: mlops-demo-datascience
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - patch
      - create
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copy-obc
  namespace: mlops-demo-datascience
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
subjects:
  - kind: ServiceAccount
    name: copy-obc
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: copy-obc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: copy-obc
  namespace: mlops-demo-pipelines
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - patch
      - create
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copy-obc
  namespace: mlops-demo-pipelines
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-5"
subjects:
  - kind: ServiceAccount
    name: copy-obc
    namespace: openshift-storage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: copy-obc