apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: copy-obc
  namespace: mlops-demo-datascience
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - patch
      - create
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copy-obc
  namespace: mlops-demo-datascience
subjects:
  - kind: ServiceAccount
    name: copy-obc
    namespace: mlops-demo-datascience
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: copy-obc
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: copy-obc
  namespace: mlops-demo-pipelines
rules:
  - apiGroups: [""]
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - patch
      - create
      - update
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: copy-obc
  namespace: mlops-demo-pipelines
subjects:
  - kind: ServiceAccount
    name: copy-obc
    namespace: mlops-demo-datascience
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: copy-obc
