apiVersion: v2
name: iris-message-generator
description: A Helm chart for Kubernetes

type: application

version: 0.1.0

dependencies:
  - name: "iris-message-generator"
    version: "0.1.0"
    repository: "file://../../../../components/charts/iris-message-generator/"
