apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "iris-inference-service.fullname" . }}
spec:
  endpoints:
    - interval: 30s
      path: /prometheus
      port: http
  selector:
    matchLabels:
      {{ include "iris-inference-service.selectorLabels" . }}