apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: iris-podmonitor
  namespace: {{ include "iris-inference-service.fullname" . }}
spec:
  podMetricsEndpoints:
    - interval: 30s
      path: /prometheus
      port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: openshift-user-workload-monitoring
      {{ include "iris-inference-service.selectorLabels" . }}
      