apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mlops-demo-gitops

bases:
  - ../../base

patches:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: mlops-demo-app-of-apps
    path: patch-app-of-apps.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
    path: patch-application-repo-revision.yaml
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
    path: patch-applicationset-repo-revision.yaml
  # Uncomment patches to disable automatic sync
  # - path: patch-applicationset-manual-sync.yaml
  #   target:
  #     group: argoproj.io
  #     version: v1alpha1
  #     kind: ApplicationSet
  # - path: patch-application-manual-sync.yaml
  #   target:
  #     group: argoproj.io
  #     kind: Application
  #     version: v1alpha1
