apiVersion: v2
name: seldon-core-analytics
description: A Helm chart for Kubernetes

type: application

version: 1.9.1

dependencies:
  - name: "seldon-core-analytics"
    version: "1.9.1"
    repository: "https://storage.googleapis.com/seldon-charts"
