apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: iris-inference-service
spec:
  params:
    - name: APP_NAME
      type: string
      default: iris-inference-service
    - name: GIT_REPO
      type: string
      default: >-
        https://github.com/rh-intelligent-application-practice/mlops-demo-iris-inference-service.git
    - name: GIT_REVISION
      type: string
      default: main
    - name: IMAGE_NAME
      type: string
      default: >-
        image-registry.openshift-image-registry.svc:5000/mlops-demo-pipelines/iris-inference-service
    - name: PATH_CONTEXT
      type: string
      default: .
    - name: VERSION
      type: string
      default: 3.9-ubi8
    - name: GITOPS_GIT_REPO
      type: string
      description: The gitops git repository url
      default: git@github.com:rh-intelligent-application-practice/mlops-demo-application-gitops.git
    - name: GITOPS_GIT_REVISION
      type: string
      default: main
      description: The gitops git repository revision
    - name: GITOPS_PATH
      type: string
      default: environments/dev/charts/iris-inference-service
      description: The location of the file to patch in the GitOps repo
  tasks:
    - name: fetch-sourcecode-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: sourcecode-workspace
    - name: test
      runAfter:
        - fetch-repository
      params:
        - name: PYTHON
          value: $(params.VERSION)
      taskRef:
        kind: Task
        name: tox
      workspaces:
        - name: source
          workspace: sourcecode-workspace
    - name: generate-tag
      runAfter:
        - test
      params:
        - name: SHA
          value: $(tasks.fetch-repository.results.commit)
      taskRef:
        kind: Task
        name: generate-tag
    - name: build
      runAfter:
        - test
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
        - name: source
          workspace: sourcecode-workspace
    - name: tag-image
      runAfter:
        - generate-tag
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc tag \
            $(params.APP_NAME)@$(tasks.build.results.IMAGE_DIGEST) \
            $(params.APP_NAME):$(tasks.generate-tag.results.image-tag)
    - name: fetch-gitops-repository
      taskRef:
        kind: ClusterTask
        name: git-clone
      params:
        - name: url
          value: $(params.GITOPS_GIT_REPO)
        - name: revision
          value: $(params.GITOPS_GIT_REVISION)
        - name: deleteExisting
          value: 'true'
      workspaces:
        - name: output
          workspace: gitops-workspace
    - name: update-values
      runAfter:
        - fetch-gitops-repository
      taskRef:
        kind: Task
        name: update-values-image-tag
      params:
        - name: fileName
          value: values.yaml
        - name: filePath
          value: $(params.GITOPS_PATH)
        - name: imageTag
          value: $(tasks.generate-tag.results.image-tag)
        - name: verbose
          value: "true"
      workspaces:
        - name: source
          workspace: gitops-workspace
    - name: push-gitops-repository
      runAfter:
        - update-values
      taskRef:
        kind: Task
        name: git-push-repository
      params:
        - name: gitRepositoryName
          value: $(params.GITOPS_GIT_REPO)
        - name: gitRepositoryRevision
          value: $(params.GITOPS_GIT_REVISION)
        - name: commitMessage
          value: "Updating Values YAML Image tag"
        - name: verbose
          value: "true"
      workspaces:
        - name: source
          workspace: gitops-workspace
  workspaces:
    - name: sourcecode-workspace
    - name: gitops-workspace
