apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: iris-inference-service
spec:
  params:
    - name: APP_NAME
      type: string
      default: iris-inference-service
    - name: GIT_REPO
      type: string
      default: >-
        https://github.com/rh-intelligent-application-practice/mlops-demo-iris-inference-service.git
    - name: GIT_REVISION
      type: string
      default: ''
    - name: IMAGE_NAME
      type: string
      default: >-
        image-registry.openshift-image-registry.svc:5000/mlops-demo-pipelines/iris-inference-service
    - name: PATH_CONTEXT
      type: string
      default: .
    - name: VERSION
      type: string
      default: 3.9-ubi8
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: test
      runAfter:
        - fetch-repository
      params:
        - name: SOURCE_PATH
          value: $(params.PATH_CONTEXT)
        - name: PYTHON
          value: $(params.VERSION)
      taskRef:
        kind: Task
        name: tox
      workspaces:
        - name: source
          workspace: workspace
    - name: generate-tag
      runAfter:
        - test
      params:
        - name: SHA
          value: $(tasks.fetch-repository.results.commit)
      taskRef:
        kind: Task
        name: generate-tag
    - name: build
      runAfter:
        - test
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: PATH_CONTEXT
          value: $(params.PATH_CONTEXT)
        - name: VERSION
          value: $(params.VERSION)
      taskRef:
        kind: ClusterTask
        name: s2i-python
      workspaces:
        - name: source
          workspace: workspace
    - name: tag-image
      runAfter:
        - generate-tag
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc tag \
            $(params.APP_NAME)@$(tasks.build.results.IMAGE_DIGEST) \
            $(params.APP_NAME):$(tasks.generate-tag.results.image-tag)
  workspaces:
    - name: workspace
