apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: iris-inference-service-
spec:
  params:
    - name: APP_NAME
      value: iris-inference-service-pipelinerun
    - name: GIT_REPO
      value: >-
        https://github.com/rh-intelligent-application-practice/mlops-demo-iris-inference-service.git
    - name: GIT_REVISION
      value: row62_AutomateInitialPipeline
    - name: IMAGE_NAME
      value: >-
        image-registry.openshift-image-registry.svc:5000/mlops-demo-pipelines/iris-inference-service
    - name: PATH_CONTEXT
      value: .
    - name: VERSION
      value: 3.9-ubi8
    - name: GITOPS_GIT_REPO
      value: >-
        git@github.com:rh-intelligent-application-practice/mlops-demo-application-gitops.git
    - name: GITOPS_GIT_REVISION
      value: row62_AutomateInitialPipeline
  pipelineRef:
    name: iris-inference-service
  serviceAccountName: pipeline
  timeout: 1h0m0s
  workspaces:
    - name: sourcecode-workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
          storageClassName: gp2
          volumeMode: Filesystem
        status: {}
    - name: gitops-workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 4Gi
          storageClassName: gp2
          volumeMode: Filesystem
        status: {}