apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - includeSelectors: true
    pairs:
      app: iris-inference-service
      app.kubernetes.io/component: pipeline
      app.kubernetes.io/instance: iris-inference-service
      app.kubernetes.io/name: iris-inference-service
      app.kubernetes.io/part-of: iris-inference-service
      pipeline.openshift.io/runtime: python
      pipeline.openshift.io/runtime-version: 3.9-ubi8
      pipeline.openshift.io/type: kubernetes

resources:
  - iris-inference-service-eventlistener.yaml
  - iris-inference-service-eventlistener-route.yaml
  - iris-inference-service-imagestream.yaml
  - iris-inference-service-pipeline.yaml
  # - iris-inference-service-pipelinerun.yaml
  - iris-inference-service-trigger-template.yaml
