apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mlops-demo-application-gitops-github-ssh-key
spec:
  encryptedData:
    ssh-privatekey: AgAilEVNrxfUAlptGAmmw8pzutkfLZi2FCutwuy7Ox175nX1ik1ntEdhl6a7TbcL2mpqss4ybxkAwvQDU5vRMZLlVir+5Q9PWz7KNlc+1HB1u2J6WeHOEfKqVwiakZqPuodiR1b0/AH/fSjFmPbgp2GvuDyYh0U3Fx9avqHFRzv+F0WEls+Ei7t1bzgPbGGYZH4c7pJtlJZyFcjWTdqYE3EbCog1t4SQeDESOX/EUXQjOtMgI9HWBVZQbUfjkkBag9O+4LAN8+bD88GbXAmLuDFBZwC9pNmwPy5/xeybC/Phvk6E6AVKa+yuxSfFNnAM266nxYVvm++WxBeoTQxrU2uLMdhX6UUbGWm6tyT2ElTij9LzAY1reucVQNR0qs1kcpSwHhUV+oFI/MoRoPyxc6YgRIla9lktcymsN6avO/Ltb2bYkGVjacaNnw5nVTPtRc5KjYkpV9VOyubYBeFrL2usc4u7B8royrJYda00al1dTVAK87hDbhitMpLDCgrg5d0RifcBzxYCLzD1aD1VjVxn0TtOJ/JsR+Z1ULuY+r8iVYG6FHmlWn3ewznEhYts+7RKsU9xN2GumeuXRICvrcxewKW7unWK5EPeqInbGHuaMyEulrMhTn00VlfeKWEK3K7tErXoUxGario7LNuaX3dtUSKr8SFSXHs8ia4i0UmJOU504cD63Q6iYDNbJh0oKnd2x57hodsyckFI8TyrHzNJAJfmLQEWkC4STAxyLNhgeHgpJBONbPehCy/hoLyYtQIZhoLSzoYgENZ6wb2F0YsyjSnA/4wDnVoc4H+AOUX4r6TctAOgHWR2zoETa3kQP2z7gG24QY2wdB3Dr3asW1LGLslxFG5z0ULtxYndsKlL2XoTrKInwVbN5tsdhnTryzSB4L32DCLSoHmnvb0tCDCbR7rJQU79Zh9eGmekpU7GZd198ZcbD0ofoPGhYRpgg+p3YbDKFv61r819uOASqy+1AVuAJ68TuDD1PlkXDeBGrmUI7cbgw986mB45l1aIeHjgV/GX7U8rrA5jp2ixunK81Gm/egI7M6sAVgpNvl9PZH8KHXzQ33Q3akY42zkoBxd7BzNwJnGh6gvTwtFagjpexg6HUXLVuKBJ+HCW5NrnJjV6ZoH2vtzu3pHdiOvyxD2FpIvLryvJMaihgUtF7bv1h26Mkd43L8DMYw8C3rI8sBBQH8c4QnPZwZemOxyDixnvcO3TWaQeh7QYGBmoOPakafbIyXemmQj9snOQg58tZk/PDjAmoKCG3A7GJ21NqGRE123msRA741W1osXJlsBmz0HjEA==
  template:
    metadata:
      annotations:
        tekton.dev/git-0: github.com
      name: mlops-demo-application-gitops-github-ssh-key
    type: kubernetes.io/ssh-auth
